### ISSUE TITLE
The label cannot multiple lines

### ISSUE THREAD

**Issue by daicaga** [tobihagemann/THLabel#39]
I created a label and set line number to 0.
But cannot show it as multiple lines.

Could you please help us to implement it?

**Comment by tobihagemann** [comment]
Hey there! I've added it in the notes, you probably missed that: https://github.com/tobihagemann/THLabel#notes

> However THLabel doesn't respect the `numberOfLines` property, because Core Text doesn't support it natively. If you would like to have multiple lines, set `lineBreakMode` to `NSLineBreakByWordWrapping`.

Hope this helps! :)

**Comment by daicaga** [comment]
Thanks, I see
