### ISSUE TITLE
Outer stroke gets messed if text contains emoji

### ISSUE THREAD

**Issue by sgil** [tobihagemann/THLabel#52]
See screenshot below for example. Happens with every font and stroke size.

```
let label = THLabel()
label.text = "hi 😊"
label.strokeSize = 4
label.strokeColor = .black
```

<img width="159" alt="Screen Shot 2021-06-01 at 12 37 22 PM" src="https://user-images.githubusercontent.com/724029/120359822-1e2d3080-c2d6-11eb-8c6c-474db49ace37.png">

**Comment by tobihagemann** [comment]
I'm unable to reproduce the issue. I used the example project from this repository (main branch). What am I missing?

<img src="https://user-images.githubusercontent.com/2924160/122921733-24f21500-d363-11eb-93df-d01fe32b04cc.png" width="390">

**Comment by sgil** [comment]
I'm sorry I was careless with the steps to reproduce. I have narrowed it down to including an emoji in the text, and setting the label's layer's masksToBounds property to false.

I can work around this issue so will close it, and you can reopen if you'd like to track that specific issue.
